---
title: "wrangling"
output: html_document
---

```{r}
library(tidyverse)
#library(plotly)
library(skimr)

```

```{r}
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

gapminder

```





```{r}
head(gapminder,6)
str(gapminder)
summary(gapminder)
skimr::skim(gapminder)

names(gapminder)
nrow(gapminder)
ncol(gapminder)
dim(gapminder)

c(nrow(gapminder),ncol(gapminder)) #same as dim


```


***dplyer**

verbs = 
*filter*
subset by row
subset by column
*mutate* = create new column

*summarize* down
*arrange* (reorder)
```{r}
#filter by rows
filter(gapminder, lifeExp <31)
filter(gapminder, country=="Mexico")

#adding two or more comparators in a text comparision using %in% and c()
filter(gapminder, country %in% c("Mexico", "Peru"))
filter(gapminder, country == "Mexico", year == 2002)
filter(gapminder, country == "Mexico", lifeExp < 50)

#find mean LifeEx of Sweden

sweden.data <- filter(gapminder, country == "Sweden")

# to select a named column of sweden.data us "$"
mean.sweden.data <- mean(sweden.data$lifeExp)


```



```{r}
select(gapminder, year, lifeExp)
select(gapminder, -continent, -lifeExp) # to exclude these columns

#use select and filter together
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)

```

***Pipes***
somewhat different than unix. have to escape operators


```{r}
gapminder %>% head(3)
gap_cambodia3 <- gapminder %>% filter(country == "Cambodia") %>% select(-continent, -lifeExp)

#clearly written: white space doesn't matter here
gap_cambodia3 <- gapminder %>%
  filter(country == "Cambodia") %>%
  select(-continent, -lifeExp)



``` 
***Mutate***

```{r}
gapminder %>% 
  mutate(index = 1:nrow(gapminder))
gapminder %>% 
  mutate(gdp= pop* gdpPercap)

egypt_vietnam <- filter (gapminder, country %in% c("Egypt", "Vietnam"))

gapminder %>%
    filter (country %in% c("Egypt", "Vietnam")) %>%
    mutate (gdp=pop*gdpPercap, max_gdp =max(gdp))


```



